import Head from "next/head";

const Counter = () => {
  return (
    <div className="p-24 w-screen min-h-screen flex justify-center items-center bg-gray-100">
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-8xl font-bold text-purple-500" data-testid="header">
          Counter Practice
        </h1>
        {/* <section className="flex flex-wrap justify-center items-baseline mt-10">
          <ul className="my-5 sm:my-10 space-y-5 bg-white p-20 rounded-xl sm:mr-10 text-left list-disc shadow-md">
            <li className="text-3xl">Update homepage at </li>
            <li className="text-3xl">Add pages to</li>
            <li className="text-3xl">Add redux slices to </li>
            <li className="text-3xl">Add tests to </li>
          </ul>
          <div className="my-5 sm:my-10 space-y-5 bg-white p-20 rounded-xl shadow-md">
            <h2 className="text-left text-4xl font-bold">Stack</h2>
            <ul className="text-left space-y-5 list-disc">
              <li className="text-3xl">NextJS</li>
              <li className="text-3xl">TailwindCSS</li>
              <li className="text-3xl">Typescript</li>
              <li className="text-3xl">Redux Toolkit</li>
              <li className="text-3xl">Jest & React Testing Library</li>
            </ul>
          </div>
        </section> */}
      </main>
    </div>
  );
};

export default Counter;
