import Head from "next/head";
import { useState } from "react";

const Counter = () => {
  const [counterValue, setCounterValue] = useState(0);
  const [inputValue, setInputValue] = useState(1);

  const addToCounter = () => {
    setCounterValue(counterValue + inputValue);
  };

  const subractFromCounter = () => {
    setCounterValue(counterValue - inputValue);
  };

  return (
    <div className="p-24 w-screen min-h-screen flex justify-center items-center bg-gray-100">
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-8xl font-bold text-purple-500" data-testid="header">
          Counter Practice
        </h1>
        <h2
          className={`my-10 text-6xl font-bold ${
            counterValue >= 100 ? "text-green-500" : ""
          } ${counterValue <= -100 ? "text-red-500" : ""}`}
          data-testid="counter"
        >
          {counterValue}
        </h2>
        <div className="flex justify-center">
          <button
            className="border border-gray-400 py-3 px-5 rounded-sm"
            data-testid="subtract-btn"
            onClick={subractFromCounter}
          >
            -
          </button>
          <input
            type="number"
            className="text-center text-2xl p-2 font-bold"
            data-testid="input"
            value={inputValue}
            onChange={(e) => setInputValue(Number(e.target.value))}
          />
          <button
            className="border border-gray-400 py-3 px-5 rounded-sm"
            data-testid="add-btn"
            onClick={addToCounter}
          >
            +
          </button>
        </div>
      </main>
    </div>
  );
};

export default Counter;
